version: '3.9'

services:
  artemis:
    image: apache/activemq-artemis:2.32.0
    container_name: artemis
    ports:
      - "8161:8161"  # Web console
      - "61616:61616"  # AMQP
      - "5672:5672"  # MQTT
      - "1883:1883"  # STOMP
      - "61613:61613"  # OpenWire
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      ANONYMOUS_LOGIN: false